#Sonar organization (required)
sonar.organization=ayusocarlos
#sonar project Key (required)
sonar.projectKey=AyusoCarlos_Rides25
#Sonar projectName. The name that appears on a Sonardashboard (required)
sonar.projectName=Rides25
#Maven version. (required)
sonar.projectVersion=0.0.1
#Path with java code (required)
sonar.sources=src
#sonar.sources=C\:\\Users\\ehu\\Desktop\\Monopoly\\src
#All paths that contain test (optional)
tests=src
#tests=C\:\\Users\\ehu\\Desktop\\Monopoly\\src
#Paths where binaries are located (required)binaries=bin
sonar.java.binaries=target 	
# The project languaje (java for defect)
sonar.language=java
sonar.host.url=https://sonarcloud.io
# Token obtained in sonarcloud that contains credentials 
sonar.login= a3e8a26de5eb463653495567ac9e69a13714f4d1
sonar.dynamicAnalysis=reuseReports